# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edson Alcala
email: edson_alcala@msn.com
description: > 
    Full Stack Web Developer with Experience in Startup and Enterprise
    environments. Windows Azure Solutions Architect    
url: "http://edsonalcala.net" # the base hostname & protocol for your site
twitter_username: EdsonAlcala
github_username:  EdsonAlcala

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "bower_components", "bower.json"]
gems:
  - jekyll-sitemap

defaults:
  - scope:
      path: "_assets/images"
    values:
      image: true