# Permalinks
permalink:      /:title

# Setup
title:          Edson Alcala
paginate:       10
baseurl:        "/"
url:            "http://www.edsonalcala.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Edson Alcala
  url:          http://edsonalcala.com
  email:        edson_alcala@msn.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/EdsonAlcala/tale

# Gems
plugins:
  - jekyll-paginate
